version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    container_name: express-api-dev
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/my-database
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
        - action: sync
          path: ./
          target: /usr/src/app
